[env]
NAME="Yugo"

[[pipes]]
name='test'
shell='''
echo $NAME
sleep 2
cal
echo "\a"
'''

[[pipes]]
name='build'
shell='''
echo 陈独秀同学，请你坐下
'''

[[pipes]]
name='deploy'
skip=true
shell='''
echo 买橘子
'''

